version: '3.8'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      - 8080:80 # local:container
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
